logger:
  level: DEBUG
  filepath: ./kafkaingest.log

nats:
  server: "nats://localhost:4222"
  stream: "NOTIFICATION_ENGINE_STREAM" # Separate inlet stream
  inlet_subject: "data.notification"
  outlet_subject: "data.elastic"
  consumer_group: "cg_notification_engine"
  durable: "nats_consumer_durable"

postgres:
  host: localhost
  port: 5432
  user: user_device_sphere
  password: p@ssw0rd@deviceSphere
  dbname: data_device_sphere
