level: DEBUG
filepath: ./natsingest.log

nats:
  server: "nats://13.200.253.161:4222"
  stream: "NOTIFICATION_ENGINE_STREAM" # Separate inlet stream
  inlet_subject: "data.ruleNotificationData"
  outlet_subject: "data.processedNotificationData"
  consumer_group: "cg_notification_engine"
  durable: "nats_consumer_durable"

postgres:
  host: "13.200.253.161"
  port: 5432
  user: user_device_sphere
  password: p@ssw0rd@deviceSphere
  dbname: data_device_sphere
