logger:
  level: DEBUG
  filepath: ./kafkaingest.log

nats:
  server: "nats://192.168.1.6:4222"
  inlet_subject: "data.processedData"
  outlet_subject: "data.notificationData"
  consumer_group: "cg_postgre_store"

postgres:
  host: "192.168.1.6"
  port: 5432
  user: user_device_sphere
  password: p@ssw0rd@deviceSphere
  dbname: data_device_sphere
