logger:
  level: DEBUG
  filepath: ./kafkaingest.log

nats:
  server: "nats://localhost:4222"
  stream: "POSTGRE_STORE_STREAM" # Separate inlet stream
  inlet_subject: "data.processedData"
  outlet_subject: "data.notificationData"
  consumer_group: "cg_postgre_store"
  durable: "nats_consumer_durable"

postgres:
  host: localhost
  port: 5432
  user: user_device_sphere
  password: p@ssw0rd@deviceSphere
  dbname: data_device_sphere
