level: DEBUG
filepath: ./natsingest.log

nats:
  server: "nats://172.31.38.233:4222"
  inlet_subject: "data.rawData"
  outlet_subject: "data.processedData"
  consumer_group: "cg_nats_ingest"

postgres:
  host: "13.200.253.161"
  port: 5432
  user: user_device_sphere
  password: p@ssw0rd@deviceSphere
  dbname: data_device_sphere
