level: DEBUG
filepath: ./natsingest.log

nats:
  server: "nats://localhost:4222"
  stream: "DEVICE_SPHERE_STREAM" # Separate inlet stream
  inlet_subject: "data.raw"
  outlet_subject: "data.processed"
  consumer_group: "cg_nats_ingest"
  durable: "nats_consumer_durable"

postgres:
  host: localhost
  port: 5432
  user: user_device_sphere
  password: p@ssw0rd@deviceSphere
  dbname: data_device_sphere
